### ISSUE TITLE
Russian translation errors

### ISSUE THREAD

**Issue by Teppy381** [axperty/storagedelight-forge#6]
1. "block.storagedelight.birch_drawer_with_door"  should be  "Берёзовый Ящик с Дверцей" (ё instead of е)
2. "block.storagedelight.spruce_single_door_cabinet"  should be  "Еловый однодверный шкаф" (instead of "Акациевый")

**Comment by axperty** [comment]
Hi Teppy381,

I recommend you to commit a pull request by making those changes in this [ru_ru.json file.](https://github.com/axperty/storagedelight/blob/1.21-forge/src/main/resources/assets/storagedelight/lang/ru_ru.json) Any changes to those files will show up in the next update of Storage Delight.

If you have any more questions, feel free to ask.

Have a good day,
Axperty.
