### ISSUE TITLE
Axe speed issue

### ISSUE THREAD

**Issue by ShyGuy001** [axperty/storagedelight-forge#9]
On version 24.8.1-1.19.2-fabric of the mod it causes axes to not break wood blocks any faster than a bare hand or any other tool

**Comment by axperty** [comment]
Hi ShyGuy001,

I'll take a look into this bug, it has happened before in newer versions, thank you for letting me know!

Have a good day,
Axperty.

**Comment by axperty** [comment]
Hi ShyGuy001,

I released an update fixing this exact problem, thank you so much!

Have a good day,
Axperty.
